### ISSUE TITLE
Is the error top-1 or top-5?

### ISSUE THREAD

**Issue by AranKomat** [noahfl/densenet-sdr#2]
The original Densenet paper's 100 layer Densenet (k=12) has error 20% on CIFAR-100, whereas this paper's same architecture without using the proposed method has 10%. So I believe the result is not top-1. If it's not top-1, what is it? If it is, then why is your baseline result much better?

**Comment by noahfl** [comment]
Apologies for the confusion. The error is top-1, but the increased batch size (100 instead of the original paper's 64) causes different results from the original paper. When setting the batch size to 64, similar results as the paper are found.

I'm honestly kind of regretting increasing the batch size as it's caused a lot of confusion despite increasing overall performance in both implementations (dropout and SDR).
